#!/usr/bin/env python3

#Модули
import os
import operator

#Рабочая директория и новый список
cd = os.getcwd()
dirs = os.listdir(cd)
allfiles = []

#Проверка существования файла и директории, с последующим добавление в наш список
for files in dirs:
    if os.path.isfile(os.path.join(cd, files)):
        size = os.path.getsize(os.path.join(cd, files))
        allfiles.append((files, size))
    if os.path.isdir(os.path.join(cd, files)):
        size = os.path.getsize(os.path.join(cd, files))
        allfiles.append((files, size))

#Обратная сортировка по размеру
allfiles.sort(key=operator.itemgetter(1), reverse=True)

#Начать нумерацию с 1 и вывести итог работы скрипта
for n, (files, size) in enumerate(allfiles, start=1):
    print("{} Файл: {:30s} Размер: {} Байт".format(n, files, size))
